In [1]:
#requirements: numpy, pandas, openpyxl, SimpleITK, pydicom, platipy
from pathlib import Path
import os
import sys
path_tot = Path(Path(os.getcwd()).parent / 'total_ROI' )
print( path_tot )
sys.path.insert(1, str(path_tot) )
import extract_histo

C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Scripts\Mix\total_ROI

In [2]:
import justified as just
import check_over as over
import check_rate as rate

In [11]:
def main():
    
    directory_out = Path.home() / "Desktop" / "Cardio" / ".venv_Fin" / "Histo_Heart" / "Analyses"
    Path(directory_out).mkdir(parents=True, exist_ok=True)  

    dir_files_fin = Path(directory_out) / "Total_ROI" / "Files_ok"
    
    if len( list(dir_files_fin.glob('*.xlsx')) ) != 0:        
        
        just_or_not = str(input("Do you want to analyze a specific region? (y/n)"))
        if "y" in just_or_not.lower():
            just_or_not = True
            print("Analyzing histograms about specific region is set on: ", just_or_not)
            print("")
    
            just.histo_just(dir_files_fin, directory_out)
            print("") 
                
        else:
            print("You preferred to not analyze the histograms about specific region.")
    
    
        check_over = str(input("\nDo you want to search patients with significative counts above an HU threshold? (y/n)"))    
        if "y" in check_over.lower():
            check_over = True
            print("Analyzing patients searching significative above specific region is set on: ", check_over)
            print("")
             
            over.check_over(dir_files_fin, directory_out)
            print("") 
            
        else:
            print("You preferred not to specifically analyze the histograms above the threshold.")
    
    
        check_rate = str(input("Do you want to search patients with a significant area outside the HU thresholds? (y/n)"))
        if "y" in check_rate.lower():
            check_rate = True
            print("Analyzing patients searching significative outside specific region is set on: ", check_rate)
            print("")
    
            rate.check_rate(dir_files_fin, directory_out)
            print("")    
                
        else:
            print("You preferred not to specifically analyze the histograms outside the HU thresholds.")
    
    else:
        print(f"You are looking at files in: \n{dir_files_fin}.")
        print("This folder is empty now.")
        print("You have to save all ROI's histogram files before analyze specific regions.")

In [12]:
if __name__ == "__main__":
    main()

Do you want to analyze a specific region? (y/n) n

You preferred to not analyze the histograms about specific region.

Do you want to search patients with significative counts above an HU threshold? (y/n) y

Analyzing patients searching significative above specific region is set on:  True

Do you want to save files and plots? (y/n) y

The saving variable is on:  True

Enter the minimum HU threshold above which to control:  -150
Enter the count threshold for significance beyond the region of interest:  150

I analyze the patient 284444
You caught a patient who has components in the indicated region.

,PatientID,Min_Region_over_-150_150,Max_Region_over_-150_150,Tot_counts_Region_over_-150_150,Mean_Region_over_-150_150,Mode_Region_over_-150_150,Count_Max_Region_over_-150_150,Median_Region_over_-150_150,Std Dev_Region_over_-150_150,Skewness_Region_over_-150_150,Kurtosis_Region_over_-150_150,10th Percentile_Region_over_-150_150,25th Percentile_Region_over_-150_150,75th Percentile_Region_over_-150_150,90th Percentile_Region_over_-150_150
0,284444,-71,75,109542,29.842554,46,2569,38.0,29.219365,-1.343155,1.41104,-14.0,19.0,49.0,58.0

Saving the patient's histogram in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_counts_regions\Region_over_-150_150\Histograms

Saving the dataframe in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_counts_regions\Region_over_-150_150\Files

I analyze the patient 298615
You caught a patient who has components in the indicated region.

,PatientID,Min_Region_over_-150_150,Max_Region_over_-150_150,Tot_counts_Region_over_-150_150,Mean_Region_over_-150_150,Mode_Region_over_-150_150,Count_Max_Region_over_-150_150,Median_Region_over_-150_150,Std Dev_Region_over_-150_150,Skewness_Region_over_-150_150,Kurtosis_Region_over_-150_150,10th Percentile_Region_over_-150_150,25th Percentile_Region_over_-150_150,75th Percentile_Region_over_-150_150,90th Percentile_Region_over_-150_150
0,298615,-71,77,118738,26.461984,40,2869,34.0,28.647902,-1.283851,1.401978,-17.0,16.0,45.0,54.0

Saving the patient's histogram in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_counts_regions\Region_over_-150_150\Histograms

Saving the dataframe in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_counts_regions\Region_over_-150_150\Files

I analyze the patient 299522
You caught a patient who has components in the indicated region.

,PatientID,Min_Region_over_-150_150,Max_Region_over_-150_150,Tot_counts_Region_over_-150_150,Mean_Region_over_-150_150,Mode_Region_over_-150_150,Count_Max_Region_over_-150_150,Median_Region_over_-150_150,Std Dev_Region_over_-150_150,Skewness_Region_over_-150_150,Kurtosis_Region_over_-150_150,10th Percentile_Region_over_-150_150,25th Percentile_Region_over_-150_150,75th Percentile_Region_over_-150_150,90th Percentile_Region_over_-150_150
0,299522,-118,68,128936,13.549079,36,2701,29.0,42.137675,-1.398918,1.099819,-58.0,1.0,41.0,51.0

Saving the patient's histogram in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_counts_regions\Region_over_-150_150\Histograms

Saving the dataframe in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_counts_regions\Region_over_-150_150\Files

Patients with significative counts over threshold are:
['284444', '298615', '299522']
Region of interest statistics saved in C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_counts_regions\Region_over_-150_150\Stats_over_-150_150.xlsx

Do you want to search patients with a significant area outside the HU thresholds? (y/n) y

Analyzing patients searching significative outside specific region is set on:  True

Do you want to save files and plots? (y/n) y

The saving variable is set on:  True

Enter the minimum HU threshold above which to check:  -150
Enter the maximum HU threshold beyond which to control:  150
Enter the threshold as a percentage of the count rate between inside and outside (-150,150):  0.5

I analyze the patient 284444
The sum of the counts in the region of interest is:  115145
The sum of the counts outside the region of interest is:  427
The rate between them is:  0.0037083677102783446

I analyze the patient 298615
The sum of the counts in the region of interest is:  125786
The sum of the counts outside the region of interest is:  662
The rate between them is:  0.005262906841778894

You have caught a patient who has significant components in the indicated region.

,PatientID,Min_Region_over_-150_150_0.5,Max_Region_over_-150_150_0.5,Tot_counts_Region_over_-150_150_0.5,Mean_Region_over_-150_150_0.5,Mode_Region_over_-150_150_0.5,Count_Max_Region_over_-150_150_0.5,Median_Region_over_-150_150_0.5,Std Dev_Region_over_-150_150_0.5,Skewness_Region_over_-150_150_0.5,Kurtosis_Region_over_-150_150_0.5,10th Percentile_Region_over_-150_150_0.5,25th Percentile_Region_over_-150_150_0.5,75th Percentile_Region_over_-150_150_0.5,90th Percentile_Region_over_-150_150_0.5
0,298615,-645,420,662,-101.521148,-154,22,-162.0,189.738328,0.797476,-0.107985,-251.0,-193.75,-151.0,204.0

Saving the patient's histogram in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_rate_regions\Region_over_-150_150_0.5\Histograms

Saving the dataframe in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_rate_regions\Region_over_-150_150_0.5\Files

I analyze the patient 299522
The sum of the counts in the region of interest is:  132039
The sum of the counts outside the region of interest is:  889
The rate between them is:  0.006732859230984785

You have caught a patient who has significant components in the indicated region.

,PatientID,Min_Region_over_-150_150_0.5,Max_Region_over_-150_150_0.5,Tot_counts_Region_over_-150_150_0.5,Mean_Region_over_-150_150_0.5,Mode_Region_over_-150_150_0.5,Count_Max_Region_over_-150_150_0.5,Median_Region_over_-150_150_0.5,Std Dev_Region_over_-150_150_0.5,Skewness_Region_over_-150_150_0.5,Kurtosis_Region_over_-150_150_0.5,10th Percentile_Region_over_-150_150_0.5,25th Percentile_Region_over_-150_150_0.5,75th Percentile_Region_over_-150_150_0.5,90th Percentile_Region_over_-150_150_0.5
0,299522,-577,-151,889,-220.195726,-159,29,-189.0,84.395061,-1.847236,3.12365,-338.0,-245.0,-162.0,-155.0

Saving the patient's histogram in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_rate_regions\Region_over_-150_150_0.5\Histograms

Saving the dataframe in  C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_rate_regions\Region_over_-150_150_0.5\Files


Patients with significative rate beetween inside and outside the region are:
['298615', '299522']
Region of interest statistics saved in C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_rate_regions\Region_over_-150_150_0.5\Stats_over_-150_150_0.5.xlsx