In [1]:
#requirements: numpy, pandas, openpyxl, SimpleITK, pydicom, platipy
# import sys
# sys.path.append("../../..")

from pathlib import Path
import Densitometry.merge_file_functions.merge_df as merge_df

In [2]:
def main():  
    # directory_out = Path.home() / "Desktop" / "Cardio" / ".venv_Fin" / "Histo_Heart" / "Analyses"
    directory_out = r"\\IHSR.dom\OSRFileServices\Ric.FisicaSanitaria\AAAshared\progetti\Adeno_Pancreas_CT\Neo_Pre"
    Path(directory_out).mkdir(parents=True, exist_ok=True)

    if "y" in str(input("Do you want to merge clinical and densitometric database? (y/n)")).lower():
        print("You chose to merge databases.")

        show_merge = str(input("\nDo you want to see all the dataframes until the final one? (y/n)"))
        save_merge = str(input("Do you want to save them? (y/n)"))
        merge_df.merge_db(directory_out, show_merge, save_merge)
    
    else:
        print("You chose not to merge databases.")
        print("")

In [3]:
if __name__ == "__main__":
    main()

You chose to merge databases.
The showing option is set on:  True
The saving option is set on:  True

The database is in: \\IHSR.dom\OSRFileServices\Ric.FisicaSanitaria\AAAshared\progetti\Adeno_Pancreas_CT\Neo_Pre\SPAARC_radiomicsResults_ROI-1__resultsTable.xlsx

,Patient,morph_volume,morph_vol_approx,morph_area_mesh,morph_av,morph_comp_1,morph_comp_2,morph_sph_dispr,morph_sphericity,morph_asphericity,...,dzm_zdnu_norm_3D,dzm_z_perc_3D,dzm_gl_var_3D,dzm_zd_var_3D,dzm_zd_entr_3D,ngt_coarseness_3D,ngt_contrast_3D,ngt_busyness_3D,ngt_complexity_3D,ngt_strength_3D
0,0000000009037089.mat,4787.8333,4813,1760.9603,0.36780,0.036554,0.47477,1.2819,0.78012,0.28186,...,0.26757,0.43964,94.2319,2.8678,7.4099,0.001874,0.137180,0.170150,5906.5516,3.1610
1,0232298.mat,6307.2083,6345,2677.0267,0.42444,0.025691,0.23451,1.6216,0.61667,0.62160,...,0.39827,0.27470,61.7063,2.0631,6.6740,0.001553,0.036598,0.195030,3432.3370,3.2050
2,100719.mat,7277.5833,7303,2257.6235,0.31022,0.038277,0.52056,1.2431,0.80443,0.24311,...,0.34588,0.28221,83.7612,2.9547,6.9586,0.001721,0.060874,0.169400,3656.9892,3.2125
3,11087435.mat,5852.7083,5880,1934.3948,0.33051,0.038812,0.53522,1.2317,0.81191,0.23166,...,0.20445,0.51327,84.3668,4.3822,7.6898,0.001294,0.185360,0.402200,5971.9486,1.5065
4,11476957.mat,2796.7083,2816,1192.1747,0.42628,0.038332,0.52207,1.2419,0.80521,0.24191,...,0.27994,0.54226,106.8469,2.0700,7.3720,0.003082,0.210230,0.151020,6541.2483,4.1330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,RM600060963.mat,929.3750,943,528.9347,0.56913,0.043104,0.66013,1.1485,0.87072,0.14848,...,0.34379,0.64581,121.2876,1.1876,7.0031,0.006833,0.374590,0.073984,8749.6952,7.6130
155,S6NBM3.mat,2327.3750,2349,1105.5517,0.47502,0.035721,0.45336,1.3017,0.76821,0.30172,...,0.32672,0.49638,90.2755,1.3945,7.0211,0.003784,0.154300,0.122180,5211.9673,4.8711
156,S8IR6P.mat,9626.9167,9657,2847.1810,0.29575,0.035751,0.45413,1.3010,0.76865,0.30099,...,0.25528,0.35373,85.2220,3.9187,7.5306,0.001108,0.083310,0.314620,4989.4248,1.9304
157,SM340100.mat,4307.4583,4332,1700.3622,0.39475,0.034660,0.42685,1.3281,0.75293,0.32814,...,0.29806,0.42082,61.0870,2.2356,7.0153,0.001788,0.113300,0.234560,4631.7184,2.2750
158,XM2415723.mat,3337.2500,3362,1648.9637,0.49411,0.028119,0.28093,1.5269,0.65494,0.52687,...,0.33978,0.52707,73.6819,1.5244,6.9413,0.002400,0.134600,0.182140,5825.8506,3.1735

The database is in: \\IHSR.dom\OSRFileServices\Ric.FisicaSanitaria\AAAshared\progetti\Adeno_Pancreas_CT\Neo_Pre\pyradiomics_features.xlsx

,Unnamed: 0,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,70803572,0.883858,0.604412,11.668483,19.305509,20.615528,23.537205,21.587033,23.727621,2625.791667,...,0.010103,0.002101,0.459534,490.840085,0.001250,0.164174,0.003225,5773.120609,0.199664,3.762687
1,IMPRM200158044,0.756063,0.634689,11.541285,18.184158,19.849433,20.124612,17.464249,21.748563,1953.750000,...,0.005612,0.001405,0.420712,609.365988,0.000938,0.094278,0.004244,5047.306511,0.156038,5.165568
2,IMP87674,0.637013,0.510889,11.375342,22.265771,23.769729,26.570661,17.464249,28.248894,1978.041667,...,0.014691,0.002284,0.324806,304.108889,0.001408,0.095183,0.005147,2998.007860,0.099307,6.416707
3,IMPCNU@000004123363,0.823822,0.547885,10.842896,19.790442,22.847319,19.235384,20.808652,25.079872,2206.291667,...,0.008570,0.002144,0.464228,499.994720,0.001322,0.111690,0.004154,6270.140306,0.166736,5.724414
4,IMP1988046748,0.704510,0.574683,19.000705,33.062948,36.235342,30.413813,34.539832,40.459857,9704.333333,...,0.009557,0.001113,0.297704,435.986008,0.000550,0.294453,0.001088,4791.664845,0.084594,1.954245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,51854081,0.697304,0.513657,13.408285,26.103582,27.202941,24.413111,23.323808,30.331502,3847.583333,...,0.007656,0.001669,0.421241,632.577787,0.000852,0.153805,0.002385,5869.396958,0.152013,3.363287
154,70421502,0.630743,0.465055,17.446939,37.515849,42.154478,40.261644,28.844410,43.139309,8757.833333,...,0.031303,0.002352,0.233375,187.628515,0.000620,0.318598,0.001816,2760.730825,0.089764,2.334945
155,IMP98156270,0.812479,0.739616,10.979044,14.844242,18.027756,15.000000,17.720045,18.055470,1212.958333,...,0.020224,0.002609,0.317210,241.548724,0.001446,0.108728,0.007646,1878.525285,0.100386,5.732659
156,IMPPG180876,0.787130,0.521518,11.637800,22.315259,24.083189,25.238859,25.709920,29.086079,2650.125000,...,0.007600,0.001913,0.398721,580.244191,0.001395,0.096265,0.003316,5992.566342,0.107456,6.122390
157,CP01015474#2044234965285190_20200730095701,0.327823,0.277169,14.960208,53.975021,51.788030,23.769729,52.810984,58.008620,8880.375000,...,0.007141,0.001098,0.401353,489.187078,0.000541,0.495844,0.000860,4791.045995,0.105111,1.032311

The columns names are:
Index(['Patient', 'morph_volume', 'morph_vol_approx', 'morph_area_mesh',
       'morph_av', 'morph_comp_1', 'morph_comp_2', 'morph_sph_dispr',
       'morph_sphericity', 'morph_asphericity',
       ...
       'dzm_zdnu_norm_3D', 'dzm_z_perc_3D', 'dzm_gl_var_3D', 'dzm_zd_var_3D',
       'dzm_zd_entr_3D', 'ngt_coarseness_3D', 'ngt_contrast_3D',
       'ngt_busyness_3D', 'ngt_complexity_3D', 'ngt_strength_3D'],
      dtype='object', length=184)



I found these columns:  ['Patient']

I found these columns:  [['Patient']]

The new column for the merge is:

0      0000000009037089mat
1               0232298mat
2                100719mat
3              11087435mat
4              11476957mat
              ...
154         rm600060963mat
155              s6nbm3mat
156              s8ir6pmat
157            sm340100mat
158           xm2415723mat
Name: LinkCol, Length: 159, dtype: object

The column for the merge is:

0      0000000009037089
1               0232298
2                100719
3              11087435
4              11476957
             ...
154         rm600060963
155              s6nbm3
156              s8ir6p
157            sm340100
158           xm2415723
Name: LinkCol, Length: 159, dtype: object

,LinkCol,Patient,morph_volume,morph_vol_approx,morph_area_mesh,morph_av,morph_comp_1,morph_comp_2,morph_sph_dispr,morph_sphericity,...,dzm_zdnu_norm_3D,dzm_z_perc_3D,dzm_gl_var_3D,dzm_zd_var_3D,dzm_zd_entr_3D,ngt_coarseness_3D,ngt_contrast_3D,ngt_busyness_3D,ngt_complexity_3D,ngt_strength_3D
0,0000000009037089,0000000009037089.mat,4787.8333,4813,1760.9603,0.36780,0.036554,0.47477,1.2819,0.78012,...,0.26757,0.43964,94.2319,2.8678,7.4099,0.001874,0.137180,0.170150,5906.5516,3.1610
1,0232298,0232298.mat,6307.2083,6345,2677.0267,0.42444,0.025691,0.23451,1.6216,0.61667,...,0.39827,0.27470,61.7063,2.0631,6.6740,0.001553,0.036598,0.195030,3432.3370,3.2050
2,100719,100719.mat,7277.5833,7303,2257.6235,0.31022,0.038277,0.52056,1.2431,0.80443,...,0.34588,0.28221,83.7612,2.9547,6.9586,0.001721,0.060874,0.169400,3656.9892,3.2125
3,11087435,11087435.mat,5852.7083,5880,1934.3948,0.33051,0.038812,0.53522,1.2317,0.81191,...,0.20445,0.51327,84.3668,4.3822,7.6898,0.001294,0.185360,0.402200,5971.9486,1.5065
4,11476957,11476957.mat,2796.7083,2816,1192.1747,0.42628,0.038332,0.52207,1.2419,0.80521,...,0.27994,0.54226,106.8469,2.0700,7.3720,0.003082,0.210230,0.151020,6541.2483,4.1330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,rm600060963,RM600060963.mat,929.3750,943,528.9347,0.56913,0.043104,0.66013,1.1485,0.87072,...,0.34379,0.64581,121.2876,1.1876,7.0031,0.006833,0.374590,0.073984,8749.6952,7.6130
155,s6nbm3,S6NBM3.mat,2327.3750,2349,1105.5517,0.47502,0.035721,0.45336,1.3017,0.76821,...,0.32672,0.49638,90.2755,1.3945,7.0211,0.003784,0.154300,0.122180,5211.9673,4.8711
156,s8ir6p,S8IR6P.mat,9626.9167,9657,2847.1810,0.29575,0.035751,0.45413,1.3010,0.76865,...,0.25528,0.35373,85.2220,3.9187,7.5306,0.001108,0.083310,0.314620,4989.4248,1.9304
157,sm340100,SM340100.mat,4307.4583,4332,1700.3622,0.39475,0.034660,0.42685,1.3281,0.75293,...,0.29806,0.42082,61.0870,2.2356,7.0153,0.001788,0.113300,0.234560,4631.7184,2.2750
158,xm2415723,XM2415723.mat,3337.2500,3362,1648.9637,0.49411,0.028119,0.28093,1.5269,0.65494,...,0.33978,0.52707,73.6819,1.5244,6.9413,0.002400,0.134600,0.182140,5825.8506,3.1735

The columns names are:
Index(['LinkCol', 'Patient', 'morph_volume', 'morph_vol_approx',
       'morph_area_mesh', 'morph_av', 'morph_comp_1', 'morph_comp_2',
       'morph_sph_dispr', 'morph_sphericity',
       ...
       'dzm_zdnu_norm_3D', 'dzm_z_perc_3D', 'dzm_gl_var_3D', 'dzm_zd_var_3D',
       'dzm_zd_entr_3D', 'ngt_coarseness_3D', 'ngt_contrast_3D',
       'ngt_busyness_3D', 'ngt_complexity_3D', 'ngt_strength_3D'],
      dtype='object', length=185)

,LinkCol,Patient,morph_volume,morph_vol_approx,morph_area_mesh,morph_av,morph_comp_1,morph_comp_2,morph_sph_dispr,morph_sphericity,...,dzm_zdnu_norm_3D,dzm_z_perc_3D,dzm_gl_var_3D,dzm_zd_var_3D,dzm_zd_entr_3D,ngt_coarseness_3D,ngt_contrast_3D,ngt_busyness_3D,ngt_complexity_3D,ngt_strength_3D
0,0000000009037089,0000000009037089.mat,4787.8333,4813,1760.9603,0.36780,0.036554,0.47477,1.2819,0.78012,...,0.26757,0.43964,94.2319,2.8678,7.4099,0.001874,0.137180,0.170150,5906.5516,3.1610
1,0232298,0232298.mat,6307.2083,6345,2677.0267,0.42444,0.025691,0.23451,1.6216,0.61667,...,0.39827,0.27470,61.7063,2.0631,6.6740,0.001553,0.036598,0.195030,3432.3370,3.2050
2,100719,100719.mat,7277.5833,7303,2257.6235,0.31022,0.038277,0.52056,1.2431,0.80443,...,0.34588,0.28221,83.7612,2.9547,6.9586,0.001721,0.060874,0.169400,3656.9892,3.2125
3,11087435,11087435.mat,5852.7083,5880,1934.3948,0.33051,0.038812,0.53522,1.2317,0.81191,...,0.20445,0.51327,84.3668,4.3822,7.6898,0.001294,0.185360,0.402200,5971.9486,1.5065
4,11476957,11476957.mat,2796.7083,2816,1192.1747,0.42628,0.038332,0.52207,1.2419,0.80521,...,0.27994,0.54226,106.8469,2.0700,7.3720,0.003082,0.210230,0.151020,6541.2483,4.1330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,rm600060963,RM600060963.mat,929.3750,943,528.9347,0.56913,0.043104,0.66013,1.1485,0.87072,...,0.34379,0.64581,121.2876,1.1876,7.0031,0.006833,0.374590,0.073984,8749.6952,7.6130
155,s6nbm3,S6NBM3.mat,2327.3750,2349,1105.5517,0.47502,0.035721,0.45336,1.3017,0.76821,...,0.32672,0.49638,90.2755,1.3945,7.0211,0.003784,0.154300,0.122180,5211.9673,4.8711
156,s8ir6p,S8IR6P.mat,9626.9167,9657,2847.1810,0.29575,0.035751,0.45413,1.3010,0.76865,...,0.25528,0.35373,85.2220,3.9187,7.5306,0.001108,0.083310,0.314620,4989.4248,1.9304
157,sm340100,SM340100.mat,4307.4583,4332,1700.3622,0.39475,0.034660,0.42685,1.3281,0.75293,...,0.29806,0.42082,61.0870,2.2356,7.0153,0.001788,0.113300,0.234560,4631.7184,2.2750
158,xm2415723,XM2415723.mat,3337.2500,3362,1648.9637,0.49411,0.028119,0.28093,1.5269,0.65494,...,0.33978,0.52707,73.6819,1.5244,6.9413,0.002400,0.134600,0.182140,5825.8506,3.1735

The columns names are:
Index(['Unnamed: 0', 'original_shape_Elongation', 'original_shape_Flatness',
       'original_shape_LeastAxisLength', 'original_shape_MajorAxisLength',
       'original_shape_Maximum2DDiameterColumn',
       'original_shape_Maximum2DDiameterRow',
       'original_shape_Maximum2DDiameterSlice',
       'original_shape_Maximum3DDiameter', 'original_shape_MeshVolume',
       ...
       'original_gldm_LargeDependenceLowGrayLevelEmphasis',
       'original_gldm_LowGrayLevelEmphasis',
       'original_gldm_SmallDependenceEmphasis',
       'original_gldm_SmallDependenceHighGrayLevelEmphasis',
       'original_gldm_SmallDependenceLowGrayLevelEmphasis',
       'original_ngtdm_Busyness', 'original_ngtdm_Coarseness',
       'original_ngtdm_Complexity', 'original_ngtdm_Contrast',
       'original_ngtdm_Strength'],
      dtype='object', length=108)



I found these columns:  ['Unnamed: 0']

I found these columns:  [['Unnamed: 0']]

The new column for the merge is:

0                                      70803572
1                                imprm200158044
2                                      imp87674
3                            impcnu000004123363
4                                 imp1988046748
                         ...
153                                    51854081
154                                    70421502
155                                 imp98156270
156                                 imppg180876
157    cp01015474204423496528519020200730095701
Name: LinkCol, Length: 158, dtype: object

The column for the merge is:

0                                      70803572
1                                imprm200158044
2                                      imp87674
3                            impcnu000004123363
4                                 imp1988046748
                         ...
153                                    51854081
154                                    70421502
155                                 imp98156270
156                                 imppg180876
157    cp01015474204423496528519020200730095701
Name: LinkCol, Length: 158, dtype: object

,LinkCol,Unnamed: 0,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,70803572,70803572,0.883858,0.604412,11.668483,19.305509,20.615528,23.537205,21.587033,23.727621,...,0.010103,0.002101,0.459534,490.840085,0.001250,0.164174,0.003225,5773.120609,0.199664,3.762687
1,imprm200158044,IMPRM200158044,0.756063,0.634689,11.541285,18.184158,19.849433,20.124612,17.464249,21.748563,...,0.005612,0.001405,0.420712,609.365988,0.000938,0.094278,0.004244,5047.306511,0.156038,5.165568
2,imp87674,IMP87674,0.637013,0.510889,11.375342,22.265771,23.769729,26.570661,17.464249,28.248894,...,0.014691,0.002284,0.324806,304.108889,0.001408,0.095183,0.005147,2998.007860,0.099307,6.416707
3,impcnu000004123363,IMPCNU@000004123363,0.823822,0.547885,10.842896,19.790442,22.847319,19.235384,20.808652,25.079872,...,0.008570,0.002144,0.464228,499.994720,0.001322,0.111690,0.004154,6270.140306,0.166736,5.724414
4,imp1988046748,IMP1988046748,0.704510,0.574683,19.000705,33.062948,36.235342,30.413813,34.539832,40.459857,...,0.009557,0.001113,0.297704,435.986008,0.000550,0.294453,0.001088,4791.664845,0.084594,1.954245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,51854081,51854081,0.697304,0.513657,13.408285,26.103582,27.202941,24.413111,23.323808,30.331502,...,0.007656,0.001669,0.421241,632.577787,0.000852,0.153805,0.002385,5869.396958,0.152013,3.363287
154,70421502,70421502,0.630743,0.465055,17.446939,37.515849,42.154478,40.261644,28.844410,43.139309,...,0.031303,0.002352,0.233375,187.628515,0.000620,0.318598,0.001816,2760.730825,0.089764,2.334945
155,imp98156270,IMP98156270,0.812479,0.739616,10.979044,14.844242,18.027756,15.000000,17.720045,18.055470,...,0.020224,0.002609,0.317210,241.548724,0.001446,0.108728,0.007646,1878.525285,0.100386,5.732659
156,imppg180876,IMPPG180876,0.787130,0.521518,11.637800,22.315259,24.083189,25.238859,25.709920,29.086079,...,0.007600,0.001913,0.398721,580.244191,0.001395,0.096265,0.003316,5992.566342,0.107456,6.122390
157,cp01015474204423496528519020200730095701,CP01015474#2044234965285190_20200730095701,0.327823,0.277169,14.960208,53.975021,51.788030,23.769729,52.810984,58.008620,...,0.007141,0.001098,0.401353,489.187078,0.000541,0.495844,0.000860,4791.045995,0.105111,1.032311

The columns names are:
Index(['LinkCol', 'Unnamed: 0', 'original_shape_Elongation',
       'original_shape_Flatness', 'original_shape_LeastAxisLength',
       'original_shape_MajorAxisLength',
       'original_shape_Maximum2DDiameterColumn',
       'original_shape_Maximum2DDiameterRow',
       'original_shape_Maximum2DDiameterSlice',
       'original_shape_Maximum3DDiameter',
       ...
       'original_gldm_LargeDependenceLowGrayLevelEmphasis',
       'original_gldm_LowGrayLevelEmphasis',
       'original_gldm_SmallDependenceEmphasis',
       'original_gldm_SmallDependenceHighGrayLevelEmphasis',
       'original_gldm_SmallDependenceLowGrayLevelEmphasis',
       'original_ngtdm_Busyness', 'original_ngtdm_Coarseness',
       'original_ngtdm_Complexity', 'original_ngtdm_Contrast',
       'original_ngtdm_Strength'],
      dtype='object', length=109)

,LinkCol,Unnamed: 0,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,70803572,70803572,0.883858,0.604412,11.668483,19.305509,20.615528,23.537205,21.587033,23.727621,...,0.010103,0.002101,0.459534,490.840085,0.001250,0.164174,0.003225,5773.120609,0.199664,3.762687
1,imprm200158044,IMPRM200158044,0.756063,0.634689,11.541285,18.184158,19.849433,20.124612,17.464249,21.748563,...,0.005612,0.001405,0.420712,609.365988,0.000938,0.094278,0.004244,5047.306511,0.156038,5.165568
2,imp87674,IMP87674,0.637013,0.510889,11.375342,22.265771,23.769729,26.570661,17.464249,28.248894,...,0.014691,0.002284,0.324806,304.108889,0.001408,0.095183,0.005147,2998.007860,0.099307,6.416707
3,impcnu000004123363,IMPCNU@000004123363,0.823822,0.547885,10.842896,19.790442,22.847319,19.235384,20.808652,25.079872,...,0.008570,0.002144,0.464228,499.994720,0.001322,0.111690,0.004154,6270.140306,0.166736,5.724414
4,imp1988046748,IMP1988046748,0.704510,0.574683,19.000705,33.062948,36.235342,30.413813,34.539832,40.459857,...,0.009557,0.001113,0.297704,435.986008,0.000550,0.294453,0.001088,4791.664845,0.084594,1.954245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,51854081,51854081,0.697304,0.513657,13.408285,26.103582,27.202941,24.413111,23.323808,30.331502,...,0.007656,0.001669,0.421241,632.577787,0.000852,0.153805,0.002385,5869.396958,0.152013,3.363287
154,70421502,70421502,0.630743,0.465055,17.446939,37.515849,42.154478,40.261644,28.844410,43.139309,...,0.031303,0.002352,0.233375,187.628515,0.000620,0.318598,0.001816,2760.730825,0.089764,2.334945
155,imp98156270,IMP98156270,0.812479,0.739616,10.979044,14.844242,18.027756,15.000000,17.720045,18.055470,...,0.020224,0.002609,0.317210,241.548724,0.001446,0.108728,0.007646,1878.525285,0.100386,5.732659
156,imppg180876,IMPPG180876,0.787130,0.521518,11.637800,22.315259,24.083189,25.238859,25.709920,29.086079,...,0.007600,0.001913,0.398721,580.244191,0.001395,0.096265,0.003316,5992.566342,0.107456,6.122390
157,cp01015474204423496528519020200730095701,CP01015474#2044234965285190_20200730095701,0.327823,0.277169,14.960208,53.975021,51.788030,23.769729,52.810984,58.008620,...,0.007141,0.001098,0.401353,489.187078,0.000541,0.495844,0.000860,4791.045995,0.105111,1.032311

The columns names of the left db are:
Index(['LinkCol', 'Patient', 'morph_volume', 'morph_vol_approx',
       'morph_area_mesh', 'morph_av', 'morph_comp_1', 'morph_comp_2',
       'morph_sph_dispr', 'morph_sphericity',
       ...
       'dzm_zdnu_norm_3D', 'dzm_z_perc_3D', 'dzm_gl_var_3D', 'dzm_zd_var_3D',
       'dzm_zd_entr_3D', 'ngt_coarseness_3D', 'ngt_contrast_3D',
       'ngt_busyness_3D', 'ngt_complexity_3D', 'ngt_strength_3D'],
      dtype='object', length=185)

The columns names of the right db are:
Index(['LinkCol', 'Unnamed: 0', 'original_shape_Elongation',
       'original_shape_Flatness', 'original_shape_LeastAxisLength',
       'original_shape_MajorAxisLength',
       'original_shape_Maximum2DDiameterColumn',
       'original_shape_Maximum2DDiameterRow',
       'original_shape_Maximum2DDiameterSlice',
       'original_shape_Maximum3DDiameter',
       ...
       'original_gldm_LargeDependenceLowGrayLevelEmphasis',
       'original_gldm_LowGrayLevelEmphasis',
       'original_gldm_SmallDependenceEmphasis',
       'original_gldm_SmallDependenceHighGrayLevelEmphasis',
       'original_gldm_SmallDependenceLowGrayLevelEmphasis',
       'original_ngtdm_Busyness', 'original_ngtdm_Coarseness',
       'original_ngtdm_Complexity', 'original_ngtdm_Contrast',
       'original_ngtdm_Strength'],
      dtype='object', length=109)

I matched the name:  LinkCol

I matched the name:  LinkCol

,LinkCol,Patient,morph_volume,morph_vol_approx,morph_area_mesh,morph_av,morph_comp_1,morph_comp_2,morph_sph_dispr,morph_sphericity,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,0000000009037089,0000000009037089.mat,4787.8333,4813,1760.9603,0.36780,0.036554,0.47477,1.2819,0.78012,...,0.006019,0.000985,0.366144,571.214475,0.000545,0.189714,0.001946,4640.309589,0.130192,2.705435
1,0232298,0232298.mat,6307.2083,6345,2677.0267,0.42444,0.025691,0.23451,1.6216,0.61667,...,0.019983,0.001093,0.183446,221.336294,0.000351,0.231622,0.001534,2256.986648,0.025078,2.987593
2,11087435,11087435.mat,5852.7083,5880,1934.3948,0.33051,0.038812,0.53522,1.2317,0.81191,...,0.008057,0.001553,0.470730,513.796048,0.000879,0.341702,0.001318,7151.817526,0.176828,1.724570
3,11476957,11476957.mat,2796.7083,2816,1192.1747,0.42628,0.038332,0.52207,1.2419,0.80521,...,0.006022,0.001472,0.477430,670.700460,0.000956,0.138991,0.003046,6981.214316,0.232975,3.968847
4,14258704,14258704.mat,8520.4583,8560,3098.5954,0.36367,0.027870,0.27598,1.5359,0.65107,...,0.008082,0.001260,0.420672,525.446424,0.000640,0.393046,0.001014,6534.187412,0.139367,1.512265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,rm600060963,RM600060963.mat,929.3750,943,528.9347,0.56913,0.043104,0.66013,1.1485,0.87072,...,0.013976,0.006630,0.604835,574.632636,0.005417,0.097004,0.006439,8377.061706,0.429104,7.053980
153,s6nbm3,S6NBM3.mat,2327.3750,2349,1105.5517,0.47502,0.035721,0.45336,1.3017,0.76821,...,0.006357,0.001619,0.471473,625.784602,0.001101,0.115062,0.003526,6612.532025,0.194531,4.700434
154,s8ir6p,S8IR6P.mat,9626.9167,9657,2847.1810,0.29575,0.035751,0.45413,1.3010,0.76865,...,0.012076,0.001333,0.313850,379.723526,0.000592,0.332173,0.001094,5215.188453,0.096579,1.816351
155,sm340100,SM340100.mat,4307.4583,4332,1700.3622,0.39475,0.034660,0.42685,1.3281,0.75293,...,0.007205,0.000958,0.344574,543.669799,0.000501,0.200978,0.001837,4088.605739,0.088607,2.340564
156,xm2415723,XM2415723.mat,3337.2500,3362,1648.9637,0.49411,0.028119,0.28093,1.5269,0.65494,...,0.007365,0.001691,0.446317,478.490861,0.001058,0.183800,0.002391,5913.167124,0.139431,3.163978

Dropped rows in df1:

,LinkCol,Patient,morph_volume,morph_vol_approx,morph_area_mesh,morph_av,morph_comp_1,morph_comp_2,morph_sph_dispr,morph_sphericity,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
2,100719,100719.mat,7277.5833,7303.0,2257.6235,0.31022,0.038277,0.52056,1.2431,0.80443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,imp11996,IMP1.1996.mat,13709.7500,13756.0,4431.7071,0.32325,0.026218,0.24423,1.5998,0.62508,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dropped rows in df2:

,LinkCol,Patient,morph_volume,morph_vol_approx,morph_area_mesh,morph_av,morph_comp_1,morph_comp_2,morph_sph_dispr,morph_sphericity,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
159,imp1199626245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.007391,0.001039,0.368676,495.481498,0.000496,0.525257,0.000633,5945.15312,0.095544,1.093883

The columns names are:
Index(['LinkCol', 'Patient', 'morph_volume', 'morph_vol_approx',
       'morph_area_mesh', 'morph_av', 'morph_comp_1', 'morph_comp_2',
       'morph_sph_dispr', 'morph_sphericity',
       ...
       'original_gldm_LargeDependenceLowGrayLevelEmphasis',
       'original_gldm_LowGrayLevelEmphasis',
       'original_gldm_SmallDependenceEmphasis',
       'original_gldm_SmallDependenceHighGrayLevelEmphasis',
       'original_gldm_SmallDependenceLowGrayLevelEmphasis',
       'original_ngtdm_Busyness', 'original_ngtdm_Coarseness',
       'original_ngtdm_Complexity', 'original_ngtdm_Contrast',
       'original_ngtdm_Strength'],
      dtype='object', length=293)

,LinkCol,Patient,morph_volume,morph_vol_approx,morph_area_mesh,morph_av,morph_comp_1,morph_comp_2,morph_sph_dispr,morph_sphericity,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,0000000009037089,0000000009037089.mat,4787.8333,4813,1760.9603,0.36780,0.036554,0.47477,1.2819,0.78012,...,0.006019,0.000985,0.366144,571.214475,0.000545,0.189714,0.001946,4640.309589,0.130192,2.705435
1,0232298,0232298.mat,6307.2083,6345,2677.0267,0.42444,0.025691,0.23451,1.6216,0.61667,...,0.019983,0.001093,0.183446,221.336294,0.000351,0.231622,0.001534,2256.986648,0.025078,2.987593
2,11087435,11087435.mat,5852.7083,5880,1934.3948,0.33051,0.038812,0.53522,1.2317,0.81191,...,0.008057,0.001553,0.470730,513.796048,0.000879,0.341702,0.001318,7151.817526,0.176828,1.724570
3,11476957,11476957.mat,2796.7083,2816,1192.1747,0.42628,0.038332,0.52207,1.2419,0.80521,...,0.006022,0.001472,0.477430,670.700460,0.000956,0.138991,0.003046,6981.214316,0.232975,3.968847
4,14258704,14258704.mat,8520.4583,8560,3098.5954,0.36367,0.027870,0.27598,1.5359,0.65107,...,0.008082,0.001260,0.420672,525.446424,0.000640,0.393046,0.001014,6534.187412,0.139367,1.512265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,rm600060963,RM600060963.mat,929.3750,943,528.9347,0.56913,0.043104,0.66013,1.1485,0.87072,...,0.013976,0.006630,0.604835,574.632636,0.005417,0.097004,0.006439,8377.061706,0.429104,7.053980
153,s6nbm3,S6NBM3.mat,2327.3750,2349,1105.5517,0.47502,0.035721,0.45336,1.3017,0.76821,...,0.006357,0.001619,0.471473,625.784602,0.001101,0.115062,0.003526,6612.532025,0.194531,4.700434
154,s8ir6p,S8IR6P.mat,9626.9167,9657,2847.1810,0.29575,0.035751,0.45413,1.3010,0.76865,...,0.012076,0.001333,0.313850,379.723526,0.000592,0.332173,0.001094,5215.188453,0.096579,1.816351
155,sm340100,SM340100.mat,4307.4583,4332,1700.3622,0.39475,0.034660,0.42685,1.3281,0.75293,...,0.007205,0.000958,0.344574,543.669799,0.000501,0.200978,0.001837,4088.605739,0.088607,2.340564
156,xm2415723,XM2415723.mat,3337.2500,3362,1648.9637,0.49411,0.028119,0.28093,1.5269,0.65494,...,0.007365,0.001691,0.446317,478.490861,0.001058,0.183800,0.002391,5913.167124,0.139431,3.163978

Saving the merged database Merge_SpAARC_Py_Adenok with not matched rows in \\IHSR.dom\OSRFileServices\Ric.FisicaSanitaria\AAAshared\progetti\Adeno_Pancreas_CT\Neo_Pre\Merged_db.



You chose to not drop patients.


Saving the merged database Merge_SpAARC_Py_Adenok with not matched rows in \\IHSR.dom\OSRFileServices\Ric.FisicaSanitaria\AAAshared\progetti\Adeno_Pancreas_CT\Neo_Pre\Merged_db.

You have finished.