In [2]:
#requirements: numpy, pandas, openpyxl, SimpleITK, pydicom, platipy

from pathlib import Path
import merge_df as merge_df

In [3]:
def main():  
    directory_out = Path.home() / "Desktop" / "Cardio" / ".venv_Fin" / "Histo_Heart" / "Analyses"
    Path(directory_out).mkdir(parents=True, exist_ok=True)

    if "y" in str(input("Do you want to merge clinical and densitometric database? (y/n)")).lower():
        print("You chose to merge databases.")

        show_merge = str(input("\nDo you want to see all the dataframes until the final one? (y/n)"))
        save_merge = str(input("Do you want to save them? (y/n)"))
        merge_df.merge_db(directory_out, show_merge, save_merge)
    
    else:
        print("You chose not to merge databases.")
        print("")

In [4]:
if __name__ == "__main__":
    main()

Do you want to merge clinical and densitometric database? (y/n) y

You chose to merge databases.

Do you want to see all the dataframes until the final one? (y/n) y
Do you want to save the final database? (y/n) n

The showing option is set on:  True
The saving option is set on:  False

Insert the name of the database:  patient

The database is in: C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\py_patient_file.xlsx

,PatientID,PatientName,PatientAge,VoxelSpacingX,VoxelSpacingY,VoxelSpacingZ,Path
0,284444,"STIZIOLI, MARISA",71,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...
1,298615,"MARI, CATERINA",66,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...
2,299522,"PANIZZOLO, NEREIDE",81,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...

Is this the file you were looking for?  y

Do you have a database that has to be merged? y

Insert the name of the database:  clinico

No Excel file found with the name 'clinico'. Try again.

Insert the name of the database:  clinic

No Excel file found with the name 'clinic'. Try again.

Insert the name of the database:  over

The database is in: C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Over_rate_regions\Region_over_-150_150_0.5\Stats_over_-150_150_0.5.xlsx

,PatientID,Min_Region_over_-150_150_0.5,Max_Region_over_-150_150_0.5,Tot_counts_Region_over_-150_150_0.5,Mean_Region_over_-150_150_0.5,Mode_Region_over_-150_150_0.5,Count_Max_Region_over_-150_150_0.5,Median_Region_over_-150_150_0.5,Std Dev_Region_over_-150_150_0.5,Skewness_Region_over_-150_150_0.5,Kurtosis_Region_over_-150_150_0.5,10th Percentile_Region_over_-150_150_0.5,25th Percentile_Region_over_-150_150_0.5,75th Percentile_Region_over_-150_150_0.5,90th Percentile_Region_over_-150_150_0.5
0,298615,-645,420,662,-101.521148,-154,22,-162,189.738328,0.797476,-0.107985,-251,-193.75,-151,204
1,299522,-577,-151,889,-220.195726,-159,29,-189,84.395061,-1.847236,3.123650,-338,-245.00,-162,-155

Is this the file you were looking for?  no

Try again.

Insert the name of the database:  specific

The database is in: C:\Users\belardo.alfonso\Desktop\Cardio\.venv_Fin\Histo_Heart\Analyses\Specific_Regions\Region_-150_150_3\Stats_specific_-150_150_3.xlsx

,PatientID,Min_Region_-150_150_3,Max_Region_-150_150_3,Tot_counts_Region_-150_150_3,Mean_Region_-150_150_3,Mode_Region_-150_150_3,Count_Max_Region_-150_150_3,Median_Region_-150_150_3,Std Dev_Region_-150_150_3,Skewness_Region_-150_150_3,Kurtosis_Region_-150_150_3,10th Percentile_Region_-150_150_3,25th Percentile_Region_-150_150_3,75th Percentile_Region_-150_150_3,90th Percentile_Region_-150_150_3
0,284444,-149,126,115066,25.815228,46,2569,38,37.131723,-1.602907,2.479805,-29.0,15,49,58
1,298615,-149,146,125736,22.355952,40,2869,33,38.042088,-1.595569,2.887948,-32.5,13,45,55
2,299522,-149,98,131974,11.709503,36,2701,28,45.634604,-1.428636,1.245722,-65.0,-2,41,51

Is this the file you were looking for?  y

Do you need to merge or modify first db columns for merging? n

Do you need to merge or modify the second db columns for merging? n

The columns names of the left db are:
Index(['PatientID', 'PatientName', 'PatientAge', 'VoxelSpacingX',
       'VoxelSpacingY', 'VoxelSpacingZ', 'Path'],
      dtype='object')

The columns names of the right db are:
Index(['PatientID', 'Min_Region_-150_150_3', 'Max_Region_-150_150_3',
       'Tot_counts_Region_-150_150_3', 'Mean_Region_-150_150_3',
       'Mode_Region_-150_150_3', 'Count_Max_Region_-150_150_3',
       'Median_Region_-150_150_3', 'Std Dev_Region_-150_150_3',
       'Skewness_Region_-150_150_3', 'Kurtosis_Region_-150_150_3',
       '10th Percentile_Region_-150_150_3',
       '25th Percentile_Region_-150_150_3',
       '75th Percentile_Region_-150_150_3',
       '90th Percentile_Region_-150_150_3'],
      dtype='object')

Which column you want to merge left db on? PatientID

I matched the name:  PatientID

Which column you want to merge right db on? PatientID

I matched the name:  PatientID

,PatientID_x,PatientName,PatientAge,VoxelSpacingX,VoxelSpacingY,VoxelSpacingZ,Path,LinkCol,PatientID_y,Min_Region_-150_150_3,...,Mode_Region_-150_150_3,Count_Max_Region_-150_150_3,Median_Region_-150_150_3,Std Dev_Region_-150_150_3,Skewness_Region_-150_150_3,Kurtosis_Region_-150_150_3,10th Percentile_Region_-150_150_3,25th Percentile_Region_-150_150_3,75th Percentile_Region_-150_150_3,90th Percentile_Region_-150_150_3
0,284444,"STIZIOLI, MARISA",71,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...,284444,284444,-149,...,46,2569,38,37.131723,-1.602907,2.479805,-29.0,15,49,58
1,298615,"MARI, CATERINA",66,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...,298615,298615,-149,...,40,2869,33,38.042088,-1.595569,2.887948,-32.5,13,45,55
2,299522,"PANIZZOLO, NEREIDE",81,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...,299522,299522,-149,...,36,2701,28,45.634604,-1.428636,1.245722,-65.0,-2,41,51

The columns names are:
Index(['PatientID_x', 'PatientName', 'PatientAge', 'VoxelSpacingX',
       'VoxelSpacingY', 'VoxelSpacingZ', 'Path', 'LinkCol', 'PatientID_y',
       'Min_Region_-150_150_3', 'Max_Region_-150_150_3',
       'Tot_counts_Region_-150_150_3', 'Mean_Region_-150_150_3',
       'Mode_Region_-150_150_3', 'Count_Max_Region_-150_150_3',
       'Median_Region_-150_150_3', 'Std Dev_Region_-150_150_3',
       'Skewness_Region_-150_150_3', 'Kurtosis_Region_-150_150_3',
       '10th Percentile_Region_-150_150_3',
       '25th Percentile_Region_-150_150_3',
       '75th Percentile_Region_-150_150_3',
       '90th Percentile_Region_-150_150_3'],
      dtype='object')

Do you want to drop a column?  y

The columns names are:
Index(['PatientID_x', 'PatientName', 'PatientAge', 'VoxelSpacingX',
       'VoxelSpacingY', 'VoxelSpacingZ', 'Path', 'LinkCol', 'PatientID_y',
       'Min_Region_-150_150_3', 'Max_Region_-150_150_3',
       'Tot_counts_Region_-150_150_3', 'Mean_Region_-150_150_3',
       'Mode_Region_-150_150_3', 'Count_Max_Region_-150_150_3',
       'Median_Region_-150_150_3', 'Std Dev_Region_-150_150_3',
       'Skewness_Region_-150_150_3', 'Kurtosis_Region_-150_150_3',
       '10th Percentile_Region_-150_150_3',
       '25th Percentile_Region_-150_150_3',
       '75th Percentile_Region_-150_150_3',
       '90th Percentile_Region_-150_150_3'],
      dtype='object')

Insert the name of the column you want to drop:  _y

I matched the name:  PatientID_y

Do you want to drop a column?  y

The columns names are:
Index(['PatientID_x', 'PatientName', 'PatientAge', 'VoxelSpacingX',
       'VoxelSpacingY', 'VoxelSpacingZ', 'Path', 'LinkCol',
       'Min_Region_-150_150_3', 'Max_Region_-150_150_3',
       'Tot_counts_Region_-150_150_3', 'Mean_Region_-150_150_3',
       'Mode_Region_-150_150_3', 'Count_Max_Region_-150_150_3',
       'Median_Region_-150_150_3', 'Std Dev_Region_-150_150_3',
       'Skewness_Region_-150_150_3', 'Kurtosis_Region_-150_150_3',
       '10th Percentile_Region_-150_150_3',
       '25th Percentile_Region_-150_150_3',
       '75th Percentile_Region_-150_150_3',
       '90th Percentile_Region_-150_150_3'],
      dtype='object')

Insert the name of the column you want to drop:  ink

I matched the name:  LinkCol

Do you want to drop a column?  n

,PatientID_x,PatientName,PatientAge,VoxelSpacingX,VoxelSpacingY,VoxelSpacingZ,Path,Min_Region_-150_150_3,Max_Region_-150_150_3,Tot_counts_Region_-150_150_3,...,Mode_Region_-150_150_3,Count_Max_Region_-150_150_3,Median_Region_-150_150_3,Std Dev_Region_-150_150_3,Skewness_Region_-150_150_3,Kurtosis_Region_-150_150_3,10th Percentile_Region_-150_150_3,25th Percentile_Region_-150_150_3,75th Percentile_Region_-150_150_3,90th Percentile_Region_-150_150_3
0,284444,"STIZIOLI, MARISA",71,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...,-149,126,115066,...,46,2569,38,37.131723,-1.602907,2.479805,-29.0,15,49,58
1,298615,"MARI, CATERINA",66,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...,-149,146,125736,...,40,2869,33,38.042088,-1.595569,2.887948,-32.5,13,45,55
2,299522,"PANIZZOLO, NEREIDE",81,0.976562,0.976562,5,C:\Users\belardo.alfonso\Desktop\Cardio\.venv_...,-149,98,131974,...,36,2701,28,45.634604,-1.428636,1.245722,-65.0,-2,41,51

Do you have a database that has to be merged? n

Do you want to drop patients from the merged db? n

You chose to not drop patients.

You have finished.